-- =======================================================
-- GYMRES - MASTER INITIALIZATION (CONSOLIDATED)
-- =======================================================

-- 1. TABLES: Unified Structure
CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    nombre TEXT DEFAULT '',
    apellido TEXT DEFAULT '',
    genero TEXT,
    rango_edad TEXT,
    rol TEXT DEFAULT 'inquilino', -- 'admin', 'inquilino', 'propietario', 'huésped'
    apartamento TEXT,
    acepta_marketing BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.reservas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE NOT NULL,
    user_name TEXT DEFAULT 'Usuario',
    date DATE NOT NULL,
    start_hour INTEGER NOT NULL,
    duration INTEGER DEFAULT 1,
    status TEXT DEFAULT 'activa',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.anuncios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    link_url TEXT,
    title TEXT DEFAULT 'Nuevos equipos disponibles',
    description TEXT DEFAULT 'Conoce las novedades del gimnasio',
    active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. SECURITY DEFINER: Safe role checking
CREATE OR REPLACE FUNCTION public.is_admin(user_uuid UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.usuarios 
        WHERE id = user_uuid AND rol = 'admin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. ENABLE RLS
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.anuncios ENABLE ROW LEVEL SECURITY;

-- 4. POLICIES: 
-- USUARIOS
DROP POLICY IF EXISTS "manage_own_profile" ON public.usuarios;
CREATE POLICY "manage_own_profile" ON public.usuarios FOR ALL USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "admin_manage_all_profiles" ON public.usuarios;
CREATE POLICY "admin_manage_all_profiles" ON public.usuarios FOR ALL USING ( public.is_admin(auth.uid()) );

-- RESERVAS
DROP POLICY IF EXISTS "user_view_own_reservations" ON public.reservas;
CREATE POLICY "user_view_own_reservations" ON public.reservas FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "user_insert_own_reservation" ON public.reservas;
CREATE POLICY "user_insert_own_reservation" ON public.reservas FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "admin_all_on_reservations" ON public.reservas;
CREATE POLICY "admin_all_on_reservations" ON public.reservas FOR ALL USING ( public.is_admin(auth.uid()) );

-- ANUNCIOS
DROP POLICY IF EXISTS "anyone_view_active_ads" ON public.anuncios;
CREATE POLICY "anyone_view_active_ads" ON public.anuncios FOR SELECT USING (active = true);
DROP POLICY IF EXISTS "admin_all_on_ads" ON public.anuncios;
CREATE POLICY "admin_all_on_ads" ON public.anuncios FOR ALL USING ( public.is_admin(auth.uid()) );

-- 5. TRIGGER: Auto-create or Update profile from metadata
-- This ensures that even if a user is deleted and recreated, the data syncs correctly.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
    INSERT INTO public.usuarios (
        id, 
        email, 
        nombre, 
        apellido, 
        rol, 
        apartamento, 
        genero, 
        rango_edad, 
        acepta_marketing
    )
    VALUES (
        new.id, 
        new.email, 
        COALESCE(new.raw_user_meta_data->>'nombre', ''),
        COALESCE(new.raw_user_meta_data->>'apellido', ''),
        COALESCE(new.raw_user_meta_data->>'rol', 'inquilino'),
        new.raw_user_meta_data->>'apartamento',
        new.raw_user_meta_data->>'genero',
        new.raw_user_meta_data->>'rango_edad',
        COALESCE((new.raw_user_meta_data->>'acepta_marketing')::boolean, true)
    )
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        nombre = EXCLUDED.nombre,
        apellido = EXCLUDED.apellido,
        rol = EXCLUDED.rol,
        apartamento = EXCLUDED.apartamento,
        genero = EXCLUDED.genero,
        rango_edad = EXCLUDED.rango_edad,
        acepta_marketing = EXCLUDED.acepta_marketing;
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. STORAGE: Announcements Setup
INSERT INTO storage.buckets (id, name, public) 
VALUES ('announcements', 'announcements', true)
ON CONFLICT (id) DO NOTHING;

-- Relaxed Storage Policies for initial success
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Admin Upload" ON storage.objects;
DROP POLICY IF EXISTS "Anyone can view announcement images" ON storage.objects;
DROP POLICY IF EXISTS "Admins can upload announcement images" ON storage.objects;

CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT USING (bucket_id = 'announcements');
CREATE POLICY "Auth Upload Access" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'announcements' AND auth.uid() IS NOT NULL);
CREATE POLICY "Auth Update Access" ON storage.objects FOR UPDATE USING (bucket_id = 'announcements' AND auth.uid() IS NOT NULL);
CREATE POLICY "Auth Delete Access" ON storage.objects FOR DELETE USING (bucket_id = 'announcements' AND auth.uid() IS NOT NULL);

-- 7. DELETE ACCOUNT: Allow users to delete their own account securely
DROP FUNCTION IF EXISTS public.delete_current_user();
CREATE OR REPLACE FUNCTION public.delete_current_user()
RETURNS void 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public
AS $$
BEGIN
    DELETE FROM auth.users WHERE id = auth.uid();
END;
$$;

GRANT EXECUTE ON FUNCTION public.delete_current_user() TO authenticated;
